version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./CrinGraph:/usr/local/apache2/htdocs
    working_dir: "/usr/local/apache2/htdocs"