version: "3.8"

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - measurements-data:/var/www/html/data
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  measurements-data:
